pretranslate:
  segments:
    ignore_frontmatter_keys:
    - "layout"
    - "permalink"
    - "noindex"
    - "date"
    - "override"
    - "codelabs"
    - "tags"
    - "authors"
  
    ignore_patterns:
    - "Native"
    - !ruby/regexp /{%\s?([a-zA-Z0-9\.\-\?\'\"\,\!\s]*)\s?%}/

  paths:
  - source: "src/site/content/en"
    include:
    - "accessible/**/index.md"
