version: 3

groups:
  # Learn CSS
  # Handles any changes related to the Learn CSS course
  learncss:
    reviewers:
      users:
      - una
      - argyleink
      teams:
      - ~web-dev-content
      - ~web-dev-eng
      - ~web-dev-approvers
    reviews:
      # Assign everyone on the content team for reviews.
      request: 99
    conditions:
      - >
        glob('src/site/content/en/learn/css/**/*.md') in files or
        glob('src/site/content/en/learn/css/**/*.yml') in files or
        glob('src/site/_data/courses/css/**/*.yml') in files

  # Content
  # Handles any changes related to site content.
  content:
    reviewers:
      teams:
      - web-dev-content
      # Prefix a username or team with ~ to include them in the reviewer pool
      # but skip them when sending review requests.
      - ~web-dev-eng
      - ~web-dev-approvers
    reviews:
      # Assign everyone on the content team for reviews.
      request: 99
    conditions:
      # Only tag the content team if the review has not been handled by
      # one of the prior teams.
      - 'len(groups.active) == 0'
      - >
        files.include('src/site/content/*') or
        files.include('src/images/authors/*') or
        files.include('src/site/_data/i18n/*') or
        files.include('src/site/_data/authorsData.json') or
        files.include('src/site/_data/tagsData.json') or
        files.include('src/site/_data/paths/*.json') or
        files.include('redirects.yaml')

  # Code
  # Handles any changes to programmatic files.
  code:
    reviewers:
      teams:
      - web-dev-eng
    reviews:
      # The number of people who should be requested for review at any given
      # time. Default is 1.
      request: 2
    conditions:
      # Only tag the eng team if the review has not been handled by
      # one of the prior teams.
      - 'len(groups.active) == 0'
      # The engineering team is the default owner for any code related files.
      - >
        contains_any_globs(files, [
          '**/*.js',
          '**/*.css',
          '**/*.scss',
          '**/*.html',
          '**/*.htm',
          '**/*.njk',
          '**/*.toml',
          '**/*.sh'
        ]) or
        files.include('*.yaml').exclude('redirects.yaml') or
        files.include('*.yml').exclude('src/site/_data/i18n/*') or
        files.include('*.json').exclude('src/site/_data/authorsData.json').exclude('src/site/_data/tagsData.json').exclude('src/site/_data/paths/*.json')
