language: node_js
node_js:
  - "10"
sudo: false
dist: trusty
git:
  depth: 1
  submodules: false
cache:
  directories:
    - node_modules
install:
  - npm ci
before_script:
  - export CHROME_PATH="$(which google-chrome-stable)"
  - google-chrome-stable --version
script:
  - npm run build
after_success:
  - npm run lhci
addons:
  chrome: stable
