language: node_js
node_js:
  - "10"
sudo: false
dist: trusty
git:
  submodules: false
cache:
  directories:
    - node_modules
install:
  - npm ci
script:
  - npm run build
after_success:
  - npm run lhci
addons:
  chrome: stable
