language: node_js
node_js:
  - "10"
sudo: false
dist: trusty
git:
  depth: 1
  submodules: false
cache:
  directories:
  - node_modules
install:
  - npm ci --ignore-scripts
script:
- ELEVENTY_ENV=prod npx eleventy
