[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/en/*/index.json"
  to = "/en/404/index.json"
  status = 404

[[redirects]]
  from = "/en/*"
  to = "/en/404/index.html"
  status = 404
