# The date is used to organize the courses on the /learn page.
# This should be the initial publish date of the course. When new pages are
# added to the course the site will check if they are <30 days old, and if they
# are, it will give them a "New" badge. However, when you first launch a course
# you don't want every entry to have a "New" badge, so anything that existed
# on or before this date will not receive the "New" badge.
date: 2022-02-01
url: /learn/images/
draft: false
title: i18n.courses.learn_images.title
description: i18n.courses.learn_images.description
# This is the logo that appears in the navigation drawer and header.
logo: '/images/courses/images/logo.svg'
# This is used to provide the background for the navigation drawer and header.
background: '/images/courses/images/background.svg'
# This provides the cover image for the card on /learn/
card: '/images/courses/images/card.svg'
# This provides the dark cover image for the card on /learn/
cardDark: '/images/courses/images/card-dark.svg'
# Abstract decorative image that's used in some card contexts
decor: '/images/courses/images/card-decor.svg'
# This is used for the social media thumbnail.
thumbnail: 'image/kheDArv5csY6rvQUJDbWRscckLr1/MadRbq0upSrYMQ1ksYrQ.png'
# This is used to color the card module count
highlight: 'magenta'
