version: 1
snapshot:
  widths: [375, 865, 1280]
  percy-css: |
    iframe {
      display: none !important;
    }
    video {
      visibility: hidden !important;
    }
agent:
  asset-discovery:
    network-idle-timeout: 250 # ms
    page-pool-size-min: 5 # pages
    page-pool-size-max: 20 # pages
