name: Cleanup old versions
on:
  schedule:
    # At 18:00 UTC / 7:00 PST every day.
    - cron: '0 18 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.1
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_KEY }}

      - name: Checkout
        uses: actions/checkout@v1.0.0

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      # Cleanup web-dev-staging
      - name: Cleanup staging
        run: npm run stage:cleanup

      # Cleanup web-dev-production-1
      - name: Cleanup prod
        run: npm run deploy:cleanup
