name: Lighthouse CI

on:
  push:
    branches:
      - main

jobs:
  lhci:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build
        env:
          ELEVENTY_ENV: prod
        run: npm ci && npm run build

      - name: Install Canary Lighthouse CI
        run: npm install @lhci/cli@next

      - name: Lighthouse CI
        run: |
          npx lhci autorun \
          --config=./tools/lhci/lighthouserc.json \
          --upload.serverBaseUrl=${{ secrets.LHCI_SERVER }} \
          --upload.token=${{ secrets.LHCI_TOKEN }}
